# Generated by Django 4.0.3 on 2022-03-08 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ProductImage',
        ),
    ]
