--
-- PostgreSQL database dump
--

-- Dumped from database version 14.7 (Ubuntu 14.7-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.7 (Ubuntu 14.7-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: UserManagement_user; Type: TABLE; Schema: public; Owner: ourbloguser
--

CREATE TABLE public."UserManagement_user" (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    email character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    tc boolean NOT NULL,
    is_active boolean NOT NULL,
    is_admin boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public."UserManagement_user" OWNER TO ourbloguser;

--
-- Name: UserManagement_user_id_seq; Type: SEQUENCE; Schema: public; Owner: ourbloguser
--

ALTER TABLE public."UserManagement_user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UserManagement_user_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: ourbloguser
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO ourbloguser;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: ourbloguser
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: ourbloguser
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO ourbloguser;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: ourbloguser
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: ourbloguser
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO ourbloguser;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: ourbloguser
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: blog_posts; Type: TABLE; Schema: public; Owner: ourbloguser
--

CREATE TABLE public.blog_posts (
    id bigint NOT NULL,
    title character varying(100) NOT NULL,
    cover_image character varying(100),
    initial_paragraph text NOT NULL,
    paragraph_heading character varying(255) NOT NULL,
    quote character varying(255),
    quote_writer character varying(255),
    second_paragraph text NOT NULL,
    paragraph_after_image text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    author_id bigint NOT NULL,
    category_id bigint NOT NULL,
    featured_posts boolean,
    most_recent_posts boolean,
    older_posts boolean,
    slug character varying(255)
);


ALTER TABLE public.blog_posts OWNER TO ourbloguser;

--
-- Name: blog_blogpost_id_seq; Type: SEQUENCE; Schema: public; Owner: ourbloguser
--

ALTER TABLE public.blog_posts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blog_blogpost_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: blog_posts_post_images; Type: TABLE; Schema: public; Owner: ourbloguser
--

CREATE TABLE public.blog_posts_post_images (
    id bigint NOT NULL,
    blogpost_id bigint NOT NULL,
    blogpostimage_id bigint NOT NULL
);


ALTER TABLE public.blog_posts_post_images OWNER TO ourbloguser;

--
-- Name: blog_blogpost_post_images_id_seq; Type: SEQUENCE; Schema: public; Owner: ourbloguser
--

ALTER TABLE public.blog_posts_post_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blog_blogpost_post_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: blog_posts_step_by_step_guide; Type: TABLE; Schema: public; Owner: ourbloguser
--

CREATE TABLE public.blog_posts_step_by_step_guide (
    id bigint NOT NULL,
    blogpost_id bigint NOT NULL,
    blogstepbystepguide_id bigint NOT NULL
);


ALTER TABLE public.blog_posts_step_by_step_guide OWNER TO ourbloguser;

--
-- Name: blog_blogpost_step_by_step_guide_id_seq; Type: SEQUENCE; Schema: public; Owner: ourbloguser
--

ALTER TABLE public.blog_posts_step_by_step_guide ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blog_blogpost_step_by_step_guide_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: blog_blogpostimage; Type: TABLE; Schema: public; Owner: ourbloguser
--

CREATE TABLE public.blog_blogpostimage (
    id bigint NOT NULL,
    images character varying(100)
);


ALTER TABLE public.blog_blogpostimage OWNER TO ourbloguser;

--
-- Name: blog_blogpostimage_id_seq; Type: SEQUENCE; Schema: public; Owner: ourbloguser
--

ALTER TABLE public.blog_blogpostimage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blog_blogpostimage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: step_by_step_guides; Type: TABLE; Schema: public; Owner: ourbloguser
--

CREATE TABLE public.step_by_step_guides (
    id bigint NOT NULL,
    sub_heading_number integer
);


ALTER TABLE public.step_by_step_guides OWNER TO ourbloguser;

--
-- Name: blog_blogpostsbsguidesubsection_id_seq; Type: SEQUENCE; Schema: public; Owner: ourbloguser
--

ALTER TABLE public.step_by_step_guides ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blog_blogpostsbsguidesubsection_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: blog_blogstepbystepguide; Type: TABLE; Schema: public; Owner: ourbloguser
--

CREATE TABLE public.blog_blogstepbystepguide (
    id bigint NOT NULL,
    main_heading character varying(255),
    main_content text,
    blog_post_id bigint,
    sbs_guide_number smallint,
    CONSTRAINT blog_blogstepbystepguide_sbs_guide_number_check CHECK ((sbs_guide_number >= 0))
);


ALTER TABLE public.blog_blogstepbystepguide OWNER TO ourbloguser;

--
-- Name: blog_blogstepbystepguide_id_seq; Type: SEQUENCE; Schema: public; Owner: ourbloguser
--

ALTER TABLE public.blog_blogstepbystepguide ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blog_blogstepbystepguide_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: blog_blogstepbystepguide_sbs_guide_sub_fields; Type: TABLE; Schema: public; Owner: ourbloguser
--

CREATE TABLE public.blog_blogstepbystepguide_sbs_guide_sub_fields (
    id bigint NOT NULL,
    blogstepbystepguide_id bigint NOT NULL,
    sbsguidesubsection_id bigint NOT NULL
);


ALTER TABLE public.blog_blogstepbystepguide_sbs_guide_sub_fields OWNER TO ourbloguser;

--
-- Name: blog_blogstepbystepguide_sbs_guide_sub_fields_id_seq; Type: SEQUENCE; Schema: public; Owner: ourbloguser
--

ALTER TABLE public.blog_blogstepbystepguide_sbs_guide_sub_fields ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blog_blogstepbystepguide_sbs_guide_sub_fields_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: blog_category; Type: TABLE; Schema: public; Owner: ourbloguser
--

CREATE TABLE public.blog_category (
    id bigint NOT NULL,
    category_name character varying(100) NOT NULL
);


ALTER TABLE public.blog_category OWNER TO ourbloguser;

--
-- Name: blog_category_id_seq; Type: SEQUENCE; Schema: public; Owner: ourbloguser
--

ALTER TABLE public.blog_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blog_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: blog_comment; Type: TABLE; Schema: public; Owner: ourbloguser
--

CREATE TABLE public.blog_comment (
    id bigint NOT NULL,
    created_date timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    comment_text text NOT NULL,
    author_id bigint NOT NULL,
    post_id bigint NOT NULL
);


ALTER TABLE public.blog_comment OWNER TO ourbloguser;

--
-- Name: blog_comment_id_seq; Type: SEQUENCE; Schema: public; Owner: ourbloguser
--

ALTER TABLE public.blog_comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blog_comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: blog_reply; Type: TABLE; Schema: public; Owner: ourbloguser
--

CREATE TABLE public.blog_reply (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    reply_text text NOT NULL,
    author_id bigint NOT NULL,
    comment_id_id bigint NOT NULL
);


ALTER TABLE public.blog_reply OWNER TO ourbloguser;

--
-- Name: blog_reply_id_seq; Type: SEQUENCE; Schema: public; Owner: ourbloguser
--

ALTER TABLE public.blog_reply ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blog_reply_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: ourbloguser
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO ourbloguser;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: ourbloguser
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: ourbloguser
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO ourbloguser;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: ourbloguser
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: ourbloguser
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO ourbloguser;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: ourbloguser
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: ourbloguser
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO ourbloguser;

--
-- Name: silk_profile; Type: TABLE; Schema: public; Owner: ourbloguser
--

CREATE TABLE public.silk_profile (
    id integer NOT NULL,
    name character varying(300) NOT NULL,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone,
    time_taken double precision,
    file_path character varying(300) NOT NULL,
    line_num integer,
    end_line_num integer,
    func_name character varying(300) NOT NULL,
    exception_raised boolean NOT NULL,
    dynamic boolean NOT NULL,
    request_id character varying(36)
);


ALTER TABLE public.silk_profile OWNER TO ourbloguser;

--
-- Name: silk_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: ourbloguser
--

ALTER TABLE public.silk_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.silk_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: silk_profile_queries; Type: TABLE; Schema: public; Owner: ourbloguser
--

CREATE TABLE public.silk_profile_queries (
    id bigint NOT NULL,
    profile_id integer NOT NULL,
    sqlquery_id integer NOT NULL
);


ALTER TABLE public.silk_profile_queries OWNER TO ourbloguser;

--
-- Name: silk_profile_queries_id_seq; Type: SEQUENCE; Schema: public; Owner: ourbloguser
--

ALTER TABLE public.silk_profile_queries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.silk_profile_queries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: silk_request; Type: TABLE; Schema: public; Owner: ourbloguser
--

CREATE TABLE public.silk_request (
    id character varying(36) NOT NULL,
    path character varying(190) NOT NULL,
    query_params text NOT NULL,
    raw_body text NOT NULL,
    body text NOT NULL,
    method character varying(10) NOT NULL,
    start_time timestamp with time zone NOT NULL,
    view_name character varying(190),
    end_time timestamp with time zone,
    time_taken double precision,
    encoded_headers text NOT NULL,
    meta_time double precision,
    meta_num_queries integer,
    meta_time_spent_queries double precision,
    pyprofile text NOT NULL,
    num_sql_queries integer NOT NULL,
    prof_file character varying(300) NOT NULL
);


ALTER TABLE public.silk_request OWNER TO ourbloguser;

--
-- Name: silk_response; Type: TABLE; Schema: public; Owner: ourbloguser
--

CREATE TABLE public.silk_response (
    id character varying(36) NOT NULL,
    status_code integer NOT NULL,
    raw_body text NOT NULL,
    body text NOT NULL,
    encoded_headers text NOT NULL,
    request_id character varying(36) NOT NULL
);


ALTER TABLE public.silk_response OWNER TO ourbloguser;

--
-- Name: silk_sqlquery; Type: TABLE; Schema: public; Owner: ourbloguser
--

CREATE TABLE public.silk_sqlquery (
    id integer NOT NULL,
    query text NOT NULL,
    start_time timestamp with time zone,
    end_time timestamp with time zone,
    time_taken double precision,
    traceback text NOT NULL,
    request_id character varying(36),
    identifier integer NOT NULL,
    analysis text
);


ALTER TABLE public.silk_sqlquery OWNER TO ourbloguser;

--
-- Name: silk_sqlquery_id_seq; Type: SEQUENCE; Schema: public; Owner: ourbloguser
--

ALTER TABLE public.silk_sqlquery ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.silk_sqlquery_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: step_by_step_guides_sub_content; Type: TABLE; Schema: public; Owner: ourbloguser
--

CREATE TABLE public.step_by_step_guides_sub_content (
    id bigint NOT NULL,
    sbsguidesubsection_id bigint NOT NULL,
    subcontent_id bigint NOT NULL
);


ALTER TABLE public.step_by_step_guides_sub_content OWNER TO ourbloguser;

--
-- Name: step_by_step_guides_sub_content_id_seq; Type: SEQUENCE; Schema: public; Owner: ourbloguser
--

ALTER TABLE public.step_by_step_guides_sub_content ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.step_by_step_guides_sub_content_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: step_by_step_guides_sub_heading; Type: TABLE; Schema: public; Owner: ourbloguser
--

CREATE TABLE public.step_by_step_guides_sub_heading (
    id bigint NOT NULL,
    sbsguidesubsection_id bigint NOT NULL,
    subheading_id bigint NOT NULL
);


ALTER TABLE public.step_by_step_guides_sub_heading OWNER TO ourbloguser;

--
-- Name: step_by_step_guides_subheadings_id_seq; Type: SEQUENCE; Schema: public; Owner: ourbloguser
--

ALTER TABLE public.step_by_step_guides_sub_heading ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.step_by_step_guides_subheadings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sub_contents; Type: TABLE; Schema: public; Owner: ourbloguser
--

CREATE TABLE public.sub_contents (
    id bigint NOT NULL,
    text text
);


ALTER TABLE public.sub_contents OWNER TO ourbloguser;

--
-- Name: sub_contents_id_seq; Type: SEQUENCE; Schema: public; Owner: ourbloguser
--

ALTER TABLE public.sub_contents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sub_contents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subheadings; Type: TABLE; Schema: public; Owner: ourbloguser
--

CREATE TABLE public.subheadings (
    id bigint NOT NULL,
    text character varying(255)
);


ALTER TABLE public.subheadings OWNER TO ourbloguser;

--
-- Name: subheadings_id_seq; Type: SEQUENCE; Schema: public; Owner: ourbloguser
--

ALTER TABLE public.subheadings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subheadings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: UserManagement_user; Type: TABLE DATA; Schema: public; Owner: ourbloguser
--

COPY public."UserManagement_user" (id, password, last_login, email, first_name, last_name, tc, is_active, is_admin, created_at, updated_at) FROM stdin;
1	pbkdf2_sha256$390000$VCd6JQkaerRLJGPzyaAhe4$oKR78ODZcTyA7lfsPLCNx8bGZJVcMM6TqjbniAP+Qyk=	2023-03-11 03:43:01.797+05	com.qandeelhaider@gmail.com	qandeel	haider	t	t	t	2023-03-11 03:40:45.465+05	2023-03-11 03:40:45.468+05
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: ourbloguser
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: ourbloguser
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: ourbloguser
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
55	Can delete reply	14	delete_reply
56	Can view reply	14	view_reply
57	Can add user	15	add_user
58	Can change user	15	change_user
59	Can delete user	15	delete_user
60	Can view user	15	view_user
61	Can add blog paragraph	16	add_blogparagraph
62	Can change blog paragraph	16	change_blogparagraph
63	Can delete blog paragraph	16	delete_blogparagraph
64	Can view blog paragraph	16	view_blogparagraph
65	Can add blog step by step guide	17	add_blogstepbystepguide
66	Can change blog step by step guide	17	change_blogstepbystepguide
67	Can delete blog step by step guide	17	delete_blogstepbystepguide
68	Can view blog step by step guide	17	view_blogstepbystepguide
69	Can add blog post sbs guide sub section	18	add_blogpostsbsguidesubsection
70	Can change blog post sbs guide sub section	18	change_blogpostsbsguidesubsection
71	Can delete blog post sbs guide sub section	18	delete_blogpostsbsguidesubsection
72	Can view blog post sbs guide sub section	18	view_blogpostsbsguidesubsection
73	Can add subcontent	19	add_subcontent
74	Can change subcontent	19	change_subcontent
75	Can delete subcontent	19	delete_subcontent
76	Can view subcontent	19	view_subcontent
77	Can add subheading	20	add_subheading
78	Can change subheading	20	change_subheading
79	Can delete subheading	20	delete_subheading
80	Can view subheading	20	view_subheading
81	Can add step-by-step guide	18	add_sbsguidesubsection
82	Can change step-by-step guide	18	change_sbsguidesubsection
83	Can delete step-by-step guide	18	delete_sbsguidesubsection
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add profile	6	add_profile
22	Can change profile	6	change_profile
23	Can delete profile	6	delete_profile
24	Can view profile	6	view_profile
25	Can add request	7	add_request
26	Can change request	7	change_request
27	Can delete request	7	delete_request
28	Can view request	7	view_request
29	Can add response	8	add_response
30	Can change response	8	change_response
31	Can delete response	8	delete_response
32	Can view response	8	view_response
33	Can add sql query	9	add_sqlquery
34	Can change sql query	9	change_sqlquery
35	Can delete sql query	9	delete_sqlquery
36	Can view sql query	9	view_sqlquery
37	Can add blog post	10	add_blogpost
38	Can change blog post	10	change_blogpost
39	Can delete blog post	10	delete_blogpost
40	Can view blog post	10	view_blogpost
41	Can add blog post image	11	add_blogpostimage
42	Can change blog post image	11	change_blogpostimage
43	Can delete blog post image	11	delete_blogpostimage
44	Can view blog post image	11	view_blogpostimage
45	Can add category	12	add_category
46	Can change category	12	change_category
47	Can delete category	12	delete_category
48	Can view category	12	view_category
49	Can add comment	13	add_comment
50	Can change comment	13	change_comment
51	Can delete comment	13	delete_comment
52	Can view comment	13	view_comment
53	Can add reply	14	add_reply
54	Can change reply	14	change_reply
84	Can view step-by-step guide	18	view_sbsguidesubsection
\.


--
-- Data for Name: blog_blogpostimage; Type: TABLE DATA; Schema: public; Owner: ourbloguser
--

COPY public.blog_blogpostimage (id, images) FROM stdin;
\.


--
-- Data for Name: blog_blogstepbystepguide; Type: TABLE DATA; Schema: public; Owner: ourbloguser
--

COPY public.blog_blogstepbystepguide (id, main_heading, main_content, blog_post_id, sbs_guide_number) FROM stdin;
6	1st sbs guide main heading	1st sbs guide meain content to look good	2	\N
\.


--
-- Data for Name: blog_blogstepbystepguide_sbs_guide_sub_fields; Type: TABLE DATA; Schema: public; Owner: ourbloguser
--

COPY public.blog_blogstepbystepguide_sbs_guide_sub_fields (id, blogstepbystepguide_id, sbsguidesubsection_id) FROM stdin;
6	6	5
7	6	6
\.


--
-- Data for Name: blog_category; Type: TABLE DATA; Schema: public; Owner: ourbloguser
--

COPY public.blog_category (id, category_name) FROM stdin;
1	SKIN-CARE TIPS
\.


--
-- Data for Name: blog_comment; Type: TABLE DATA; Schema: public; Owner: ourbloguser
--

COPY public.blog_comment (id, created_date, updated_at, comment_text, author_id, post_id) FROM stdin;
\.


--
-- Data for Name: blog_posts; Type: TABLE DATA; Schema: public; Owner: ourbloguser
--

COPY public.blog_posts (id, title, cover_image, initial_paragraph, paragraph_heading, quote, quote_writer, second_paragraph, paragraph_after_image, created_at, updated_at, author_id, category_id, featured_posts, most_recent_posts, older_posts, slug) FROM stdin;
1	Dark Circles During a Week of *Very* Little Sleep	blog-images/GettyImages.jpg	If you’ve been searching for a serum that's gentle enough for the delicate skin around your eyes but is also efficacious, this one's for you. Youth to the People (YTTP)—the California-based skin-care brand known for its plant-derived formulas and commitment to sustainability—just launched the Peptides + C Energy Eye Concentrate ($48), which promises to immediately illuminate and visibly brighten dark undereye circles and reduce puffiness.\r\n\r\nThe gel-serum formula packs a one-two punch of vitamin C and peptides (along with caffeine, the best-of-the-best ingredient for faking a full night's sleep), which work synergistically and “complement each other, as vitamin c is an antioxidant that helps provide environmental protection and peptides help stimulate collagen and repair,” says Michele Farber, MD, FAAD, a board-certified dermatologist with the Schweiger Dermatology Group in Philadelphia, PA.\r\nThis all sounds incredible, but if I’m being honest, I’m a little reluctant when it comes to eye products. I don’t expect miracle results, but I’ve been burned in the past with products that have extraordinary claims but really don’t do much at all. This product was different. After testing it out during one very sleep-deprived week with three sick kids under the age of 7, my under-eye area looks visibly brighter and my dark circles are not as pronounced. Keep reading to find out more.	What happened when I tried it	\N	\N	The YTTP team recommends integrating the serum into your a.m. and p.m. routines, so that's exactly what I did. After I wash my face, I massage one to two pumps of Energy Eye under and around my eye area until it’s fully absorbed and top it off with my usual Doré La Crème Daily Moisturizer ($36).\r\n\r\nThe eye concentrate has a smooth satin texture with a cooling effect upon application—two things that will make you want to use the product over and over. “[After ingredients], it’s really about texture and performance," says Gonzalez. "The best formulas are the products that you use consistently. You can have the best-sounding thing on paper but if you can’t use it all the time, you’re not going to use those benefits. Skin care needs consistency.” I, for one, genuinely enjoyed the ritual of using it every morning and evening.\r\n\r\nMy honest thoughts? I came in with a healthy dose of skepticism but truly love the product. I plan on continuing to use it in my morning and evening skincare routines for a much-needed energy boost around my eyes.		2023-03-11 03:19:42+05	2023-03-11 05:42:29.162+05	1	1	f	t	f	\N
2	How To Wash Towels Correctly—Because We’re Definitely All Making the Same Mistake	blog-images/wash-towel.jpg	It is a common laundry mistake to think that more is better when washing towels. Too often, people use more laundry detergent than is needed and additives like fabric softener and dryer sheets. According to “The Laundry Evangelist” Patric Richardson: “These aren’t necessary.” Not only will they do more harm than good to towels, they can also shorten their lifespan. With this in mind, Richardson and other laundry experts share how to wash towels the right way—your best bath towels deserve nothing less.	How To Wash Towels the Right Way: 4 Tips & Tricks	\N	\N	When washing towels—or anything else, for that matter—you only need two tablespoons of laundry detergent per load. “It sounds counterintuitive,” says Richardson, “but people get crunchy towels or towels that smell sour or musty because they use too much detergent.” What’s more, excessive detergent can leave towels dirtier, rather than cleaner, in the long term. As Hampr laundry expert Kate Hanks told Well+Good, it causes build-up between fibers which hold on dirt and bacteria.		2023-03-11 03:44:38+05	2023-03-12 07:15:16.737+05	1	1	f	t	f	\N
\.


--
-- Data for Name: blog_posts_post_images; Type: TABLE DATA; Schema: public; Owner: ourbloguser
--

COPY public.blog_posts_post_images (id, blogpost_id, blogpostimage_id) FROM stdin;
\.


--
-- Data for Name: blog_posts_step_by_step_guide; Type: TABLE DATA; Schema: public; Owner: ourbloguser
--

COPY public.blog_posts_step_by_step_guide (id, blogpost_id, blogstepbystepguide_id) FROM stdin;
5	2	6
\.


--
-- Data for Name: blog_reply; Type: TABLE DATA; Schema: public; Owner: ourbloguser
--

COPY public.blog_reply (id, created_at, updated_at, reply_text, author_id, comment_id_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: ourbloguser
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
4	2023-03-11 05:41:03.038+05	2	How To Wash Towels Correctly—Because We’re Definitely All Making the Same Mistake	2	[{"changed": {"fields": ["Cover image"]}}]	10	1
5	2023-03-11 05:42:29.165+05	1	Dark Circles During a Week of *Very* Little Sleep	2	[{"changed": {"fields": ["Cover image"]}}]	10	1
6	2023-03-12 05:40:00.829+05	1	BlogPostSBSGuideSubSection object (1)	1	[{"added": {}}]	18	1
7	2023-03-12 05:40:16.498+05	1	BlogStepByStepGuide object (1)	1	[{"added": {}}]	17	1
8	2023-03-12 05:44:28.575+05	2	BlogStepByStepGuide object (2)	1	[{"added": {}}]	17	1
9	2023-03-12 05:44:33.946+05	2	How To Wash Towels Correctly—Because We’re Definitely All Making the Same Mistake	2	[{"changed": {"fields": ["Step by step guide"]}}]	10	1
10	2023-03-12 05:46:59.865+05	2	BlogPostSBSGuideSubSection object (2)	1	[{"added": {}}]	18	1
11	2023-03-12 05:47:01.691+05	3	BlogStepByStepGuide object (3)	1	[{"added": {}}]	17	1
12	2023-03-12 05:47:03.752+05	2	How To Wash Towels Correctly—Because We’re Definitely All Making the Same Mistake	2	[{"changed": {"fields": ["Step by step guide"]}}]	10	1
13	2023-03-12 06:00:32.023+05	2	BlogPostSBSGuideSubSection object (2)	3		18	1
14	2023-03-12 06:00:32.025+05	1	BlogPostSBSGuideSubSection object (1)	3		18	1
15	2023-03-12 06:13:05.451+05	3	BlogStepByStepGuide object (3)	3		17	1
16	2023-03-12 06:13:05.453+05	2	BlogStepByStepGuide object (2)	3		17	1
17	2023-03-12 06:13:05.455+05	1	BlogStepByStepGuide object (1)	3		17	1
18	2023-03-12 06:31:58.522+05	1	1st subheading for sbs guide	1	[{"added": {}}]	20	1
19	2023-03-12 06:32:16.837+05	1	1st sub content for the sbs guide so that it looks good	1	[{"added": {}}]	19	1
20	2023-03-12 06:32:54.202+05	2	2nd subheading for the sbs guid	1	[{"added": {}}]	20	1
21	2023-03-12 06:33:08.109+05	2	2nd sub content for the sbs guide so that it looks good	1	[{"added": {}}]	19	1
22	2023-03-12 06:33:09.55+05	3	BlogPostSBSGuideSubSection object (3)	1	[{"added": {}}]	18	1
23	2023-03-12 06:33:14.321+05	4	BlogStepByStepGuide object (4)	1	[{"added": {}}]	17	1
24	2023-03-12 06:33:19.85+05	2	How To Wash Towels Correctly—Because We’re Definitely All Making the Same Mistake	2	[{"changed": {"fields": ["Step by step guide"]}}]	10	1
25	2023-03-12 06:38:31.339+05	4	BlogStepByStepGuide object (4)	2	[{"changed": {"fields": ["Main heading", "Main content"]}}]	17	1
26	2023-03-12 06:40:06.343+05	3	1st subheading of 2nd sbs guide	1	[{"added": {}}]	20	1
27	2023-03-12 06:40:23.878+05	3	1st sub content of the 2nd sbs guide of the same blog post	1	[{"added": {}}]	19	1
1	2023-03-11 03:55:00.742+05	1	SKIN-CARE TIPS	1	[{"added": {}}]	12	1
2	2023-03-11 03:55:09.579+05	1	Dark Circles During a Week of *Very* Little Sleep	1	[{"added": {}}]	10	1
3	2023-03-11 03:56:29.982+05	2	How To Wash Towels Correctly—Because We’re Definitely All Making the Same Mistake	1	[{"added": {}}]	10	1
28	2023-03-12 06:40:25.031+05	4	BlogPostSBSGuideSubSection object (4)	1	[{"added": {}}]	18	1
29	2023-03-12 06:40:29.6+05	5	BlogStepByStepGuide object (5)	1	[{"added": {}}]	17	1
30	2023-03-12 06:40:31.839+05	2	How To Wash Towels Correctly—Because We’re Definitely All Making the Same Mistake	2	[{"changed": {"fields": ["Step by step guide"]}}]	10	1
31	2023-03-12 07:12:51.731+05	5	BlogStepByStepGuide object (5)	3		17	1
32	2023-03-12 07:12:51.734+05	4	BlogStepByStepGuide object (4)	3		17	1
33	2023-03-12 07:14:45.301+05	5	BlogPostSBSGuideSubSection object (5)	1	[{"added": {}}]	18	1
34	2023-03-12 07:15:08.248+05	6	BlogPostSBSGuideSubSection object (6)	1	[{"added": {}}]	18	1
35	2023-03-12 07:15:09.103+05	6	BlogStepByStepGuide object (6)	1	[{"added": {}}]	17	1
36	2023-03-12 07:15:16.742+05	2	How To Wash Towels Correctly—Because We’re Definitely All Making the Same Mistake	2	[{"changed": {"fields": ["Step by step guide"]}}]	10	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: ourbloguser
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	silk	profile
7	silk	request
8	silk	response
9	silk	sqlquery
10	blog	blogpost
11	blog	blogpostimage
12	blog	category
13	blog	comment
14	blog	reply
15	UserManagement	user
16	blog	blogparagraph
17	blog	blogstepbystepguide
18	blog	sbsguidesubsection
19	blog	subcontent
20	blog	subheading
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: ourbloguser
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	UserManagement	0001_initial	2023-03-11 03:36:24.613865+05
2	contenttypes	0001_initial	2023-03-11 03:36:24.624009+05
3	admin	0001_initial	2023-03-11 03:36:24.688437+05
4	admin	0002_logentry_remove_auto_add	2023-03-11 03:36:24.693649+05
5	admin	0003_logentry_add_action_flag_choices	2023-03-11 03:36:24.699602+05
6	contenttypes	0002_remove_content_type_name	2023-03-11 03:36:24.714537+05
7	auth	0001_initial	2023-03-11 03:36:24.760009+05
8	auth	0002_alter_permission_name_max_length	2023-03-11 03:36:24.768228+05
9	auth	0003_alter_user_email_max_length	2023-03-11 03:36:24.774845+05
10	auth	0004_alter_user_username_opts	2023-03-11 03:36:24.782037+05
11	auth	0005_alter_user_last_login_null	2023-03-11 03:36:24.789599+05
12	auth	0006_require_contenttypes_0002	2023-03-11 03:36:24.791913+05
13	auth	0007_alter_validators_add_error_messages	2023-03-11 03:36:24.800458+05
14	auth	0008_alter_user_username_max_length	2023-03-11 03:36:24.807239+05
15	auth	0009_alter_user_last_name_max_length	2023-03-11 03:36:24.813536+05
16	auth	0010_alter_group_name_max_length	2023-03-11 03:36:24.822802+05
17	auth	0011_update_proxy_permissions	2023-03-11 03:36:24.830767+05
18	auth	0012_alter_user_first_name_max_length	2023-03-11 03:36:24.838037+05
19	blog	0001_initial	2023-03-11 03:36:24.943814+05
20	blog	0002_rename_author_name_comment_author_and_more	2023-03-11 03:36:24.979928+05
21	blog	0003_rename_author_id_blogpost_author	2023-03-11 03:36:24.995265+05
22	blog	0004_blogpost_featured_blogpost_most_recent_and_more	2023-03-11 03:36:25.031536+05
23	blog	0005_rename_featured_blogpost_featured_posts_and_more	2023-03-11 03:36:25.055978+05
24	blog	0006_alter_blogpost_paragraph_after_image_and_more	2023-03-11 03:36:25.076145+05
25	blog	0007_alter_blogpost_created_at	2023-03-11 03:36:25.087548+05
26	blog	0008_alter_blogpost_created_at	2023-03-11 03:36:25.097689+05
27	blog	0009_alter_blogpost_created_at	2023-03-11 03:36:25.111277+05
28	blog	0010_alter_blogpost_created_at	2023-03-11 03:36:25.121557+05
29	blog	0011_alter_blogpost_created_at_alter_blogpost_quote_and_more	2023-03-11 03:36:25.149007+05
30	blog	0012_alter_blogpost_created_at	2023-03-11 03:36:25.160312+05
31	blog	0013_alter_blogpost_created_at	2023-03-11 03:36:25.170094+05
32	sessions	0001_initial	2023-03-11 03:36:25.185473+05
33	silk	0001_initial	2023-03-11 03:36:25.277808+05
34	silk	0002_auto_update_uuid4_id_field	2023-03-11 03:36:25.293245+05
35	silk	0003_request_prof_file	2023-03-11 03:36:25.301586+05
36	silk	0004_request_prof_file_storage	2023-03-11 03:36:25.308579+05
37	silk	0005_increase_request_prof_file_length	2023-03-11 03:36:25.314648+05
38	silk	0006_fix_request_prof_file_blank	2023-03-11 03:36:25.321753+05
39	silk	0007_sqlquery_identifier	2023-03-11 03:36:25.330477+05
40	silk	0008_sqlquery_analysis	2023-03-11 03:36:25.338585+05
41	blog	0014_alter_blogpost_created_at	2023-03-11 03:39:52.271702+05
42	blog	0015_alter_blogpost_cover_image_alter_blogpost_created_at	2023-03-11 03:45:13.298955+05
43	blog	0002_alter_blogpost_created_at	2023-03-11 06:31:09.928583+05
44	blog	0003_alter_blogpost_created_at_alter_blogpost_post_images_and_more	2023-03-12 04:50:45.752954+05
45	blog	0004_blogstepbystepguide_remove_blogpost_paragraphs_and_more	2023-03-12 05:03:53.872796+05
46	blog	0005_remove_blogstepbystepguide_sub_content_and_more	2023-03-12 05:14:44.796644+05
47	blog	0006_blogstepbystepguide_sbs_guide_sub_fields_and_more	2023-03-12 05:21:07.692804+05
48	blog	0007_alter_blogpost_created_at_and_more	2023-03-12 05:30:28.331306+05
49	blog	0008_remove_blogpostsbsguidesubsection_blog_step_and_more	2023-03-12 05:31:58.712746+05
50	blog	0011_alter_blogpost_created_at	2023-03-12 05:37:42.075847+05
51	blog	0012_alter_blogpost_created_at_alter_blogpost_post_images	2023-03-12 05:42:14.048222+05
52	blog	0013_alter_blogpost_created_at_alter_blogpost_post_images	2023-03-12 05:43:30.412651+05
53	blog	0014_subcontent_subheading_and_more	2023-03-12 06:12:29.115014+05
54	blog	0015_remove_blogpostsbsguidesubsection_blog_post_and_more	2023-03-12 06:26:09.837804+05
55	blog	0016_rename_subheadings_blogpostsbsguidesubsection_sub_heading_and_more	2023-03-12 07:10:16.075727+05
56	blog	0017_alter_blogpost_created_at	2023-03-12 07:10:16.089817+05
57	blog	0018_blogpostsbsguidesubsection_sub_heading_number_and_more	2023-03-12 07:35:39.799272+05
58	blog	0019_rename_blogpostsbsguidesubsection_sbsguidesubsection_and_more	2023-03-12 08:14:45.558388+05
59	blog	0020_blogstepbystepguide_sbs_guide_number_and_more	2023-03-12 08:26:12.122897+05
60	blog	0021_alter_blogpost_created_at	2023-03-12 08:26:59.168228+05
61	blog	0022_alter_blogpost_options_blogpost_slug_and_more	2023-03-12 18:34:35.532218+05
62	blog	0003_alter_blogpost_created_at	2023-03-12 18:54:18.346799+05
63	blog	0004_alter_blogpost_created_at	2023-03-12 18:54:18.365315+05
64	blog	0005_alter_blogpost_created_at	2023-03-12 18:57:26.366483+05
65	blog	0006_alter_blogpost_created_at	2023-03-12 19:04:36.175708+05
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: ourbloguser
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
jw0eoblxxatkn6jpvcanf5mqxpw7ikct	.eJxVjMEOwiAQRP-FsyGsLJR69O43kF2WStXQpLQn47_bJj3ocea9mbeKtC4lri3PcRR1UaBOvx1Teua6A3lQvU86TXWZR9a7og_a9G2S_Loe7t9BoVa2tcfOkssps0cGRxYJydCWLDFYkcEI0BkweefYBQMc-gH7YCl0xgf1-QLptDeK:1palS1:TTRePEubBSiCC59QwSA62R6H27g3wcYEvMKKPtMnmmk	2023-03-25 03:43:01.799+05
\.


--
-- Data for Name: silk_profile; Type: TABLE DATA; Schema: public; Owner: ourbloguser
--

COPY public.silk_profile (id, name, start_time, end_time, time_taken, file_path, line_num, end_line_num, func_name, exception_raised, dynamic, request_id) FROM stdin;
\.


--
-- Data for Name: silk_profile_queries; Type: TABLE DATA; Schema: public; Owner: ourbloguser
--

COPY public.silk_profile_queries (id, profile_id, sqlquery_id) FROM stdin;
\.


--
-- Data for Name: silk_request; Type: TABLE DATA; Schema: public; Owner: ourbloguser
--

COPY public.silk_request (id, path, query_params, raw_body, body, method, start_time, view_name, end_time, time_taken, encoded_headers, meta_time, meta_num_queries, meta_time_spent_queries, pyprofile, num_sql_queries, prof_file) FROM stdin;
\.


--
-- Data for Name: silk_response; Type: TABLE DATA; Schema: public; Owner: ourbloguser
--

COPY public.silk_response (id, status_code, raw_body, body, encoded_headers, request_id) FROM stdin;
\.


--
-- Data for Name: silk_sqlquery; Type: TABLE DATA; Schema: public; Owner: ourbloguser
--

COPY public.silk_sqlquery (id, query, start_time, end_time, time_taken, traceback, request_id, identifier, analysis) FROM stdin;
\.


--
-- Data for Name: step_by_step_guides; Type: TABLE DATA; Schema: public; Owner: ourbloguser
--

COPY public.step_by_step_guides (id, sub_heading_number) FROM stdin;
3	\N
4	\N
5	\N
6	\N
\.


--
-- Data for Name: step_by_step_guides_sub_content; Type: TABLE DATA; Schema: public; Owner: ourbloguser
--

COPY public.step_by_step_guides_sub_content (id, sbsguidesubsection_id, subcontent_id) FROM stdin;
1	3	1
2	3	2
3	4	3
4	5	1
5	6	2
\.


--
-- Data for Name: step_by_step_guides_sub_heading; Type: TABLE DATA; Schema: public; Owner: ourbloguser
--

COPY public.step_by_step_guides_sub_heading (id, sbsguidesubsection_id, subheading_id) FROM stdin;
1	3	1
2	3	2
3	4	3
4	5	1
5	6	2
\.


--
-- Data for Name: sub_contents; Type: TABLE DATA; Schema: public; Owner: ourbloguser
--

COPY public.sub_contents (id, text) FROM stdin;
1	1st sub content for the sbs guide so that it looks good
2	2nd sub content for the sbs guide so that it looks good
3	1st sub content of the 2nd sbs guide of the same blog post
\.


--
-- Data for Name: subheadings; Type: TABLE DATA; Schema: public; Owner: ourbloguser
--

COPY public.subheadings (id, text) FROM stdin;
1	1st subheading for sbs guide
2	2nd subheading for the sbs guid
3	1st subheading of 2nd sbs guide
\.


--
-- Name: UserManagement_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ourbloguser
--

SELECT pg_catalog.setval('public."UserManagement_user_id_seq"', 1, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ourbloguser
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ourbloguser
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ourbloguser
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 84, true);


--
-- Name: blog_blogpost_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ourbloguser
--

SELECT pg_catalog.setval('public.blog_blogpost_id_seq', 2, true);


--
-- Name: blog_blogpost_post_images_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ourbloguser
--

SELECT pg_catalog.setval('public.blog_blogpost_post_images_id_seq', 1, false);


--
-- Name: blog_blogpost_step_by_step_guide_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ourbloguser
--

SELECT pg_catalog.setval('public.blog_blogpost_step_by_step_guide_id_seq', 5, true);


--
-- Name: blog_blogpostimage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ourbloguser
--

SELECT pg_catalog.setval('public.blog_blogpostimage_id_seq', 1, false);


--
-- Name: blog_blogpostsbsguidesubsection_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ourbloguser
--

SELECT pg_catalog.setval('public.blog_blogpostsbsguidesubsection_id_seq', 6, true);


--
-- Name: blog_blogstepbystepguide_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ourbloguser
--

SELECT pg_catalog.setval('public.blog_blogstepbystepguide_id_seq', 6, true);


--
-- Name: blog_blogstepbystepguide_sbs_guide_sub_fields_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ourbloguser
--

SELECT pg_catalog.setval('public.blog_blogstepbystepguide_sbs_guide_sub_fields_id_seq', 7, true);


--
-- Name: blog_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ourbloguser
--

SELECT pg_catalog.setval('public.blog_category_id_seq', 1, true);


--
-- Name: blog_comment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ourbloguser
--

SELECT pg_catalog.setval('public.blog_comment_id_seq', 1, false);


--
-- Name: blog_reply_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ourbloguser
--

SELECT pg_catalog.setval('public.blog_reply_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ourbloguser
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 36, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ourbloguser
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 20, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ourbloguser
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 65, true);


--
-- Name: silk_profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ourbloguser
--

SELECT pg_catalog.setval('public.silk_profile_id_seq', 1, false);


--
-- Name: silk_profile_queries_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ourbloguser
--

SELECT pg_catalog.setval('public.silk_profile_queries_id_seq', 1, false);


--
-- Name: silk_sqlquery_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ourbloguser
--

SELECT pg_catalog.setval('public.silk_sqlquery_id_seq', 1, false);


--
-- Name: step_by_step_guides_sub_content_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ourbloguser
--

SELECT pg_catalog.setval('public.step_by_step_guides_sub_content_id_seq', 5, true);


--
-- Name: step_by_step_guides_subheadings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ourbloguser
--

SELECT pg_catalog.setval('public.step_by_step_guides_subheadings_id_seq', 5, true);


--
-- Name: sub_contents_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ourbloguser
--

SELECT pg_catalog.setval('public.sub_contents_id_seq', 3, true);


--
-- Name: subheadings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ourbloguser
--

SELECT pg_catalog.setval('public.subheadings_id_seq', 3, true);


--
-- Name: UserManagement_user UserManagement_user_email_key; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public."UserManagement_user"
    ADD CONSTRAINT "UserManagement_user_email_key" UNIQUE (email);


--
-- Name: UserManagement_user UserManagement_user_pkey; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public."UserManagement_user"
    ADD CONSTRAINT "UserManagement_user_pkey" PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: blog_posts blog_blogpost_pkey; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.blog_posts
    ADD CONSTRAINT blog_blogpost_pkey PRIMARY KEY (id);


--
-- Name: blog_posts_post_images blog_blogpost_post_image_blogpost_id_blogpostimag_0b1d67ea_uniq; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.blog_posts_post_images
    ADD CONSTRAINT blog_blogpost_post_image_blogpost_id_blogpostimag_0b1d67ea_uniq UNIQUE (blogpost_id, blogpostimage_id);


--
-- Name: blog_posts_post_images blog_blogpost_post_images_pkey; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.blog_posts_post_images
    ADD CONSTRAINT blog_blogpost_post_images_pkey PRIMARY KEY (id);


--
-- Name: blog_posts blog_blogpost_slug_key; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.blog_posts
    ADD CONSTRAINT blog_blogpost_slug_key UNIQUE (slug);


--
-- Name: blog_posts_step_by_step_guide blog_blogpost_step_by_st_blogpost_id_blogstepbyst_56e95b9a_uniq; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.blog_posts_step_by_step_guide
    ADD CONSTRAINT blog_blogpost_step_by_st_blogpost_id_blogstepbyst_56e95b9a_uniq UNIQUE (blogpost_id, blogstepbystepguide_id);


--
-- Name: blog_posts_step_by_step_guide blog_blogpost_step_by_step_guide_pkey; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.blog_posts_step_by_step_guide
    ADD CONSTRAINT blog_blogpost_step_by_step_guide_pkey PRIMARY KEY (id);


--
-- Name: blog_blogpostimage blog_blogpostimage_pkey; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.blog_blogpostimage
    ADD CONSTRAINT blog_blogpostimage_pkey PRIMARY KEY (id);


--
-- Name: step_by_step_guides blog_blogpostsbsguidesubsection_pkey; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.step_by_step_guides
    ADD CONSTRAINT blog_blogpostsbsguidesubsection_pkey PRIMARY KEY (id);


--
-- Name: blog_blogstepbystepguide_sbs_guide_sub_fields blog_blogstepbystepguide_blogstepbystepguide_id_b_24f5f415_uniq; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.blog_blogstepbystepguide_sbs_guide_sub_fields
    ADD CONSTRAINT blog_blogstepbystepguide_blogstepbystepguide_id_b_24f5f415_uniq UNIQUE (blogstepbystepguide_id, sbsguidesubsection_id);


--
-- Name: blog_blogstepbystepguide blog_blogstepbystepguide_pkey; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.blog_blogstepbystepguide
    ADD CONSTRAINT blog_blogstepbystepguide_pkey PRIMARY KEY (id);


--
-- Name: blog_blogstepbystepguide_sbs_guide_sub_fields blog_blogstepbystepguide_sbs_guide_sub_fields_pkey; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.blog_blogstepbystepguide_sbs_guide_sub_fields
    ADD CONSTRAINT blog_blogstepbystepguide_sbs_guide_sub_fields_pkey PRIMARY KEY (id);


--
-- Name: blog_category blog_category_pkey; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.blog_category
    ADD CONSTRAINT blog_category_pkey PRIMARY KEY (id);


--
-- Name: blog_comment blog_comment_pkey; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.blog_comment
    ADD CONSTRAINT blog_comment_pkey PRIMARY KEY (id);


--
-- Name: blog_reply blog_reply_pkey; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.blog_reply
    ADD CONSTRAINT blog_reply_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: silk_profile silk_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.silk_profile
    ADD CONSTRAINT silk_profile_pkey PRIMARY KEY (id);


--
-- Name: silk_profile_queries silk_profile_queries_pkey; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.silk_profile_queries
    ADD CONSTRAINT silk_profile_queries_pkey PRIMARY KEY (id);


--
-- Name: silk_profile_queries silk_profile_queries_profile_id_sqlquery_id_b2403d9b_uniq; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.silk_profile_queries
    ADD CONSTRAINT silk_profile_queries_profile_id_sqlquery_id_b2403d9b_uniq UNIQUE (profile_id, sqlquery_id);


--
-- Name: silk_request silk_request_pkey; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.silk_request
    ADD CONSTRAINT silk_request_pkey PRIMARY KEY (id);


--
-- Name: silk_response silk_response_pkey; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.silk_response
    ADD CONSTRAINT silk_response_pkey PRIMARY KEY (id);


--
-- Name: silk_response silk_response_request_id_key; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.silk_response
    ADD CONSTRAINT silk_response_request_id_key UNIQUE (request_id);


--
-- Name: silk_sqlquery silk_sqlquery_pkey; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.silk_sqlquery
    ADD CONSTRAINT silk_sqlquery_pkey PRIMARY KEY (id);


--
-- Name: step_by_step_guides_sub_content step_by_step_guides_sub__blogpostsbsguidesubsecti_302531c2_uniq; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.step_by_step_guides_sub_content
    ADD CONSTRAINT step_by_step_guides_sub__blogpostsbsguidesubsecti_302531c2_uniq UNIQUE (sbsguidesubsection_id, subcontent_id);


--
-- Name: step_by_step_guides_sub_content step_by_step_guides_sub_content_pkey; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.step_by_step_guides_sub_content
    ADD CONSTRAINT step_by_step_guides_sub_content_pkey PRIMARY KEY (id);


--
-- Name: step_by_step_guides_sub_heading step_by_step_guides_subh_blogpostsbsguidesubsecti_e72e53b3_uniq; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.step_by_step_guides_sub_heading
    ADD CONSTRAINT step_by_step_guides_subh_blogpostsbsguidesubsecti_e72e53b3_uniq UNIQUE (sbsguidesubsection_id, subheading_id);


--
-- Name: step_by_step_guides_sub_heading step_by_step_guides_subheadings_pkey; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.step_by_step_guides_sub_heading
    ADD CONSTRAINT step_by_step_guides_subheadings_pkey PRIMARY KEY (id);


--
-- Name: sub_contents sub_contents_pkey; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.sub_contents
    ADD CONSTRAINT sub_contents_pkey PRIMARY KEY (id);


--
-- Name: subheadings subheadings_pkey; Type: CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.subheadings
    ADD CONSTRAINT subheadings_pkey PRIMARY KEY (id);


--
-- Name: UserManagement_user_email_6674a52f_like; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX "UserManagement_user_email_6674a52f_like" ON public."UserManagement_user" USING btree (email varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: blog_blogpost_author_id_id_7efef6a3; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX blog_blogpost_author_id_id_7efef6a3 ON public.blog_posts USING btree (author_id);


--
-- Name: blog_blogpost_category_id_0e9835dd; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX blog_blogpost_category_id_0e9835dd ON public.blog_posts USING btree (category_id);


--
-- Name: blog_blogpost_post_images_blogpost_id_c046cfb7; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX blog_blogpost_post_images_blogpost_id_c046cfb7 ON public.blog_posts_post_images USING btree (blogpost_id);


--
-- Name: blog_blogpost_post_images_blogpostimage_id_6fb69cbd; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX blog_blogpost_post_images_blogpostimage_id_6fb69cbd ON public.blog_posts_post_images USING btree (blogpostimage_id);


--
-- Name: blog_blogpost_step_by_step_blogstepbystepguide_id_caa21ee1; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX blog_blogpost_step_by_step_blogstepbystepguide_id_caa21ee1 ON public.blog_posts_step_by_step_guide USING btree (blogstepbystepguide_id);


--
-- Name: blog_blogpost_step_by_step_guide_blogpost_id_4eefbf49; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX blog_blogpost_step_by_step_guide_blogpost_id_4eefbf49 ON public.blog_posts_step_by_step_guide USING btree (blogpost_id);


--
-- Name: blog_blogstepbystepguide_blog_post_id_660b254b; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX blog_blogstepbystepguide_blog_post_id_660b254b ON public.blog_blogstepbystepguide USING btree (blog_post_id);


--
-- Name: blog_blogstepbystepguide_s_blogpostsbsguidesubsection_6aa0c6de; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX blog_blogstepbystepguide_s_blogpostsbsguidesubsection_6aa0c6de ON public.blog_blogstepbystepguide_sbs_guide_sub_fields USING btree (sbsguidesubsection_id);


--
-- Name: blog_blogstepbystepguide_s_blogstepbystepguide_id_07441dc8; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX blog_blogstepbystepguide_s_blogstepbystepguide_id_07441dc8 ON public.blog_blogstepbystepguide_sbs_guide_sub_fields USING btree (blogstepbystepguide_id);


--
-- Name: blog_comment_author_name_id_96e8326d; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX blog_comment_author_name_id_96e8326d ON public.blog_comment USING btree (author_id);


--
-- Name: blog_comment_post_id_580e96ef; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX blog_comment_post_id_580e96ef ON public.blog_comment USING btree (post_id);


--
-- Name: blog_posts_slug_93227477_like; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX blog_posts_slug_93227477_like ON public.blog_posts USING btree (slug varchar_pattern_ops);


--
-- Name: blog_reply_author_id_id_26c55454; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX blog_reply_author_id_id_26c55454 ON public.blog_reply USING btree (author_id);


--
-- Name: blog_reply_comment_id_id_4d0f35cc; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX blog_reply_comment_id_id_4d0f35cc ON public.blog_reply USING btree (comment_id_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: silk_profile_queries_profile_id_a3d76db8; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX silk_profile_queries_profile_id_a3d76db8 ON public.silk_profile_queries USING btree (profile_id);


--
-- Name: silk_profile_queries_sqlquery_id_155df455; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX silk_profile_queries_sqlquery_id_155df455 ON public.silk_profile_queries USING btree (sqlquery_id);


--
-- Name: silk_profile_request_id_7b81bd69; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX silk_profile_request_id_7b81bd69 ON public.silk_profile USING btree (request_id);


--
-- Name: silk_profile_request_id_7b81bd69_like; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX silk_profile_request_id_7b81bd69_like ON public.silk_profile USING btree (request_id varchar_pattern_ops);


--
-- Name: silk_request_id_5a356c4f_like; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX silk_request_id_5a356c4f_like ON public.silk_request USING btree (id varchar_pattern_ops);


--
-- Name: silk_request_path_9f3d798e; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX silk_request_path_9f3d798e ON public.silk_request USING btree (path);


--
-- Name: silk_request_path_9f3d798e_like; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX silk_request_path_9f3d798e_like ON public.silk_request USING btree (path varchar_pattern_ops);


--
-- Name: silk_request_start_time_1300bc58; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX silk_request_start_time_1300bc58 ON public.silk_request USING btree (start_time);


--
-- Name: silk_request_view_name_68559f7b; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX silk_request_view_name_68559f7b ON public.silk_request USING btree (view_name);


--
-- Name: silk_request_view_name_68559f7b_like; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX silk_request_view_name_68559f7b_like ON public.silk_request USING btree (view_name varchar_pattern_ops);


--
-- Name: silk_response_id_dda88710_like; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX silk_response_id_dda88710_like ON public.silk_response USING btree (id varchar_pattern_ops);


--
-- Name: silk_response_request_id_1e8e2776_like; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX silk_response_request_id_1e8e2776_like ON public.silk_response USING btree (request_id varchar_pattern_ops);


--
-- Name: silk_sqlquery_request_id_6f8f0527; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX silk_sqlquery_request_id_6f8f0527 ON public.silk_sqlquery USING btree (request_id);


--
-- Name: silk_sqlquery_request_id_6f8f0527_like; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX silk_sqlquery_request_id_6f8f0527_like ON public.silk_sqlquery USING btree (request_id varchar_pattern_ops);


--
-- Name: step_by_step_guides_sub_co_blogpostsbsguidesubsection_a4c5d284; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX step_by_step_guides_sub_co_blogpostsbsguidesubsection_a4c5d284 ON public.step_by_step_guides_sub_content USING btree (sbsguidesubsection_id);


--
-- Name: step_by_step_guides_sub_content_subcontent_id_0a7e762e; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX step_by_step_guides_sub_content_subcontent_id_0a7e762e ON public.step_by_step_guides_sub_content USING btree (subcontent_id);


--
-- Name: step_by_step_guides_subhea_blogpostsbsguidesubsection_a9b1376a; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX step_by_step_guides_subhea_blogpostsbsguidesubsection_a9b1376a ON public.step_by_step_guides_sub_heading USING btree (sbsguidesubsection_id);


--
-- Name: step_by_step_guides_subheadings_subheading_id_ddcbdb0d; Type: INDEX; Schema: public; Owner: ourbloguser
--

CREATE INDEX step_by_step_guides_subheadings_subheading_id_ddcbdb0d ON public.step_by_step_guides_sub_heading USING btree (subheading_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: blog_posts blog_blogpost_author_id_ffcc150f_fk_UserManagement_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.blog_posts
    ADD CONSTRAINT "blog_blogpost_author_id_ffcc150f_fk_UserManagement_user_id" FOREIGN KEY (author_id) REFERENCES public."UserManagement_user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: blog_posts blog_blogpost_category_id_0e9835dd_fk_blog_category_id; Type: FK CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.blog_posts
    ADD CONSTRAINT blog_blogpost_category_id_0e9835dd_fk_blog_category_id FOREIGN KEY (category_id) REFERENCES public.blog_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: blog_posts_post_images blog_blogpost_post_i_blogpost_id_c046cfb7_fk_blog_blog; Type: FK CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.blog_posts_post_images
    ADD CONSTRAINT blog_blogpost_post_i_blogpost_id_c046cfb7_fk_blog_blog FOREIGN KEY (blogpost_id) REFERENCES public.blog_posts(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: blog_posts_post_images blog_blogpost_post_i_blogpostimage_id_6fb69cbd_fk_blog_blog; Type: FK CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.blog_posts_post_images
    ADD CONSTRAINT blog_blogpost_post_i_blogpostimage_id_6fb69cbd_fk_blog_blog FOREIGN KEY (blogpostimage_id) REFERENCES public.blog_blogpostimage(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: blog_posts_step_by_step_guide blog_blogpost_step_b_blogpost_id_4eefbf49_fk_blog_blog; Type: FK CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.blog_posts_step_by_step_guide
    ADD CONSTRAINT blog_blogpost_step_b_blogpost_id_4eefbf49_fk_blog_blog FOREIGN KEY (blogpost_id) REFERENCES public.blog_posts(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: blog_posts_step_by_step_guide blog_blogpost_step_b_blogstepbystepguide__caa21ee1_fk_blog_blog; Type: FK CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.blog_posts_step_by_step_guide
    ADD CONSTRAINT blog_blogpost_step_b_blogstepbystepguide__caa21ee1_fk_blog_blog FOREIGN KEY (blogstepbystepguide_id) REFERENCES public.blog_blogstepbystepguide(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: blog_blogstepbystepguide blog_blogstepbystepg_blog_post_id_660b254b_fk_blog_blog; Type: FK CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.blog_blogstepbystepguide
    ADD CONSTRAINT blog_blogstepbystepg_blog_post_id_660b254b_fk_blog_blog FOREIGN KEY (blog_post_id) REFERENCES public.blog_posts(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: blog_blogstepbystepguide_sbs_guide_sub_fields blog_blogstepbystepg_blogstepbystepguide__07441dc8_fk_blog_blog; Type: FK CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.blog_blogstepbystepguide_sbs_guide_sub_fields
    ADD CONSTRAINT blog_blogstepbystepg_blogstepbystepguide__07441dc8_fk_blog_blog FOREIGN KEY (blogstepbystepguide_id) REFERENCES public.blog_blogstepbystepguide(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: blog_blogstepbystepguide_sbs_guide_sub_fields blog_blogstepbystepg_sbsguidesubsection_i_61e02a67_fk_step_by_s; Type: FK CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.blog_blogstepbystepguide_sbs_guide_sub_fields
    ADD CONSTRAINT blog_blogstepbystepg_sbsguidesubsection_i_61e02a67_fk_step_by_s FOREIGN KEY (sbsguidesubsection_id) REFERENCES public.step_by_step_guides(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: blog_comment blog_comment_author_id_4f11e2e0_fk_UserManagement_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.blog_comment
    ADD CONSTRAINT "blog_comment_author_id_4f11e2e0_fk_UserManagement_user_id" FOREIGN KEY (author_id) REFERENCES public."UserManagement_user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: blog_comment blog_comment_post_id_580e96ef_fk_blog_blogpost_id; Type: FK CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.blog_comment
    ADD CONSTRAINT blog_comment_post_id_580e96ef_fk_blog_blogpost_id FOREIGN KEY (post_id) REFERENCES public.blog_posts(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: blog_reply blog_reply_author_id_7641dac7_fk_UserManagement_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.blog_reply
    ADD CONSTRAINT "blog_reply_author_id_7641dac7_fk_UserManagement_user_id" FOREIGN KEY (author_id) REFERENCES public."UserManagement_user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: blog_reply blog_reply_comment_id_id_4d0f35cc_fk_blog_comment_id; Type: FK CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.blog_reply
    ADD CONSTRAINT blog_reply_comment_id_id_4d0f35cc_fk_blog_comment_id FOREIGN KEY (comment_id_id) REFERENCES public.blog_comment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_UserManagement_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_UserManagement_user_id" FOREIGN KEY (user_id) REFERENCES public."UserManagement_user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: silk_profile_queries silk_profile_queries_profile_id_a3d76db8_fk_silk_profile_id; Type: FK CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.silk_profile_queries
    ADD CONSTRAINT silk_profile_queries_profile_id_a3d76db8_fk_silk_profile_id FOREIGN KEY (profile_id) REFERENCES public.silk_profile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: silk_profile_queries silk_profile_queries_sqlquery_id_155df455_fk_silk_sqlquery_id; Type: FK CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.silk_profile_queries
    ADD CONSTRAINT silk_profile_queries_sqlquery_id_155df455_fk_silk_sqlquery_id FOREIGN KEY (sqlquery_id) REFERENCES public.silk_sqlquery(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: silk_profile silk_profile_request_id_7b81bd69_fk_silk_request_id; Type: FK CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.silk_profile
    ADD CONSTRAINT silk_profile_request_id_7b81bd69_fk_silk_request_id FOREIGN KEY (request_id) REFERENCES public.silk_request(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: silk_response silk_response_request_id_1e8e2776_fk_silk_request_id; Type: FK CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.silk_response
    ADD CONSTRAINT silk_response_request_id_1e8e2776_fk_silk_request_id FOREIGN KEY (request_id) REFERENCES public.silk_request(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: silk_sqlquery silk_sqlquery_request_id_6f8f0527_fk_silk_request_id; Type: FK CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.silk_sqlquery
    ADD CONSTRAINT silk_sqlquery_request_id_6f8f0527_fk_silk_request_id FOREIGN KEY (request_id) REFERENCES public.silk_request(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: step_by_step_guides_sub_content step_by_step_guides__sbsguidesubsection_i_429eb17b_fk_step_by_s; Type: FK CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.step_by_step_guides_sub_content
    ADD CONSTRAINT step_by_step_guides__sbsguidesubsection_i_429eb17b_fk_step_by_s FOREIGN KEY (sbsguidesubsection_id) REFERENCES public.step_by_step_guides(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: step_by_step_guides_sub_heading step_by_step_guides__sbsguidesubsection_i_ea847996_fk_step_by_s; Type: FK CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.step_by_step_guides_sub_heading
    ADD CONSTRAINT step_by_step_guides__sbsguidesubsection_i_ea847996_fk_step_by_s FOREIGN KEY (sbsguidesubsection_id) REFERENCES public.step_by_step_guides(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: step_by_step_guides_sub_content step_by_step_guides__subcontent_id_0a7e762e_fk_sub_conte; Type: FK CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.step_by_step_guides_sub_content
    ADD CONSTRAINT step_by_step_guides__subcontent_id_0a7e762e_fk_sub_conte FOREIGN KEY (subcontent_id) REFERENCES public.sub_contents(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: step_by_step_guides_sub_heading step_by_step_guides__subheading_id_ddcbdb0d_fk_subheadin; Type: FK CONSTRAINT; Schema: public; Owner: ourbloguser
--

ALTER TABLE ONLY public.step_by_step_guides_sub_heading
    ADD CONSTRAINT step_by_step_guides__subheading_id_ddcbdb0d_fk_subheadin FOREIGN KEY (subheading_id) REFERENCES public.subheadings(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

