# Generated by Django 4.1.7 on 2023-03-20 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the terms and conditions.', max_length=255)),
                ('content', models.TextField(help_text='The content of the terms and conditions.')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Terms and Conditions',
            },
        ),
        migrations.CreateModel(
            name='UserAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_date', models.DateTimeField(auto_now_add=True)),
                ('terms_and_conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_agreements', to='legal.termsandconditions')),
                ('user', models.ForeignKey(help_text='The user of agreement.', on_delete=django.db.models.deletion.CASCADE, related_name='user_agreements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Agreements',
            },
        ),
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue_title', models.CharField(help_text='The title of the clause.', max_length=255)),
                ('clue_content', models.TextField(help_text='The content of the clause.')),
                ('order', models.PositiveIntegerField(help_text='The order in which the clause should appear in the terms and conditions.')),
                ('terms_and_conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='legal.termsandconditions')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
