# Generated by Django 4.1.6 on 2023-07-06 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meta', '0003_alter_seo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertiseWithWellPlusGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the about page.', max_length=100)),
                ('content', models.TextField(blank=True, help_text='The content of the about page.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time when the contact us page was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the contact us post was last updated.')),
                ('author_advertise_well_good', models.ForeignKey(help_text='The author of the contact us page.', on_delete=django.db.models.deletion.CASCADE, related_name='advertise_well_good', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Advertise-with-well-plus-good',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the about page.', max_length=100)),
                ('content', models.TextField(blank=True, help_text='The content of the about page.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time when the contact us page was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the contact us post was last updated.')),
                ('author', models.ForeignKey(help_text='The author of the contact us page.', on_delete=django.db.models.deletion.CASCADE, related_name='author_contact_us', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'contact us',
                'db_table': 'contact_us',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_title', models.CharField(blank=True, help_text='The title of the clause..', max_length=255, null=True)),
                ('paragraph_content', models.TextField(blank=True, help_text='The content of the clause..', null=True)),
                ('order', models.PositiveIntegerField(blank=True, default=0, help_text='The order in which the clause should appear in the terms and conditions..', null=True)),
                ('advertise_with_us', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertise_with_us', to='page.advertisewithwellplusgood')),
                ('contact_us', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_paragraphs', to='page.contactus')),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the about page.', max_length=100)),
                ('content', models.TextField(blank=True, help_text='The content of the about page.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time when the privacy policy page was created.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_privacy_policy', models.ForeignKey(blank=True, help_text='The author of the privacy policy us page.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_privacy_policy', to=settings.AUTH_USER_MODEL)),
                ('paragraphs_privacy_policy', models.ManyToManyField(blank=True, related_name='privacy_policy', to='page.paragraph')),
                ('seo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='privacy_policy', to='meta.seo')),
            ],
            options={
                'verbose_name_plural': 'Privacy Policy',
                'db_table': 'PrivacyPolicy',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StepByStepGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_style', models.CharField(blank=True, choices=[('simple', 'Simple'), ('bulleted', 'Bulleted'), ('numbered', 'Numbered'), ('asterisk', 'Asterisk'), ('dotted', 'Dotted')], default='simple', help_text='The list style of the paragraph.', max_length=50, null=True)),
                ('sbs_guide_number', models.PositiveSmallIntegerField(blank=True, help_text='Number of the step-by-step guides on a post. Can be used for multiple purposes.', null=True)),
                ('sub_heading', models.CharField(blank=True, help_text='The text of this subheading.', max_length=255, null=True)),
                ('sub_content', models.TextField(blank=True, help_text='The text of this subcontent.', null=True)),
                ('sbs_index', models.PositiveSmallIntegerField(blank=True, help_text='The number of this subsection within the parent step-by-step guide.', null=True)),
                ('blog_paragraphs', models.ForeignKey(blank=True, help_text='The blog post that this step-by-step guide belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_paragraphs', to='page.paragraph')),
                ('contact_us', models.ForeignKey(help_text='The post that this step-by-step guide belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='step_by_step_guides_contact_specific', to='page.contactus')),
                ('privacy_policy', models.ForeignKey(blank=True, help_text='The post that this step-by-step guide belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='privacy_policy', to='page.privacypolicy')),
                ('sbs_self_refer', models.ForeignKey(blank=True, help_text='The parent subsection that this subsection belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sbsguides', to='page.stepbystepguide')),
            ],
            options={
                'verbose_name': 'step-by-step guide',
                'verbose_name_plural': 'step-by-step guides',
                'db_table': 'step_by_step_guides_contact_us_specific',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='paragraph',
            name='step_by_step_guide',
            field=models.ManyToManyField(blank=True, related_name='posts_sbs', to='page.stepbystepguide'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='paragraphs',
            field=models.ManyToManyField(blank=True, related_name='paragraphs_contact_us', to='page.paragraph'),
        ),
        migrations.AddField(
            model_name='advertisewithwellplusgood',
            name='paragraphs_advertise_well_good',
            field=models.ManyToManyField(blank=True, related_name='paragraphs_advertise_well_good', to='page.paragraph'),
        ),
    ]
