# Generated by Django 4.1.6 on 2023-07-06 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='privacypolicy',
            table='privacy_policy',
        ),
    ]
