# Generated by Django 4.1.6 on 2023-07-06 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_privacypolicy_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacypolicy',
            name='paragraphs_privacy_policy',
        ),
    ]
