# Generated by Django 4.1.6 on 2023-07-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_alter_privacypolicy_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='myImage',
            field=models.ImageField(blank=True, null=True, upload_to='space-lifesyncnow/media'),
        ),
    ]
