# Generated by Django 4.1.6 on 2023-07-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_privacypolicy_myimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisewithwellplusgood',
            name='paragraphs_advertise_well_good',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='paragraphs',
        ),
    ]
