# Generated by Django 4.1.6 on 2023-07-06 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seo',
            options={'verbose_name': 'SEO'},
        ),
        migrations.AlterModelTable(
            name='seo',
            table='my_seo_table',
        ),
    ]
