# Generated by Django 4.1.6 on 2023-07-06 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_alter_seo_options_alter_seo_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seo',
            options={'verbose_name': 'SEO', 'verbose_name_plural': 'SEO'},
        ),
    ]
