# Generated by Django 4.1.6 on 2023-07-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0003_alter_seo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='meta_description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
