# Generated by Django 4.1.6 on 2023-07-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0004_alter_seo_meta_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seo',
            options={'verbose_name': 'seo', 'verbose_name_plural': 'seo'},
        ),
    ]
