# Generated by Django 4.1.6 on 2023-07-06 11:55

from django.db import migrations, models
import django.db.models.deletion
import global_content.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_link', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter_link', models.URLField(blank=True, max_length=255, null=True)),
                ('instagram_link', models.URLField(blank=True, max_length=255, null=True)),
                ('youtube_link', models.URLField(blank=True, max_length=255, null=True)),
                ('pinterest_link', models.URLField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Follow Up',
                'verbose_name_plural': 'Follow Ups',
                'db_table': 'follow_up',
            },
        ),
        migrations.CreateModel(
            name='PageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_name', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_description', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='template-images/', validators=[global_content.models.validate_image])),
                ('copyright', models.CharField(blank=True, max_length=255, null=True)),
                ('follow_us', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_us_page_template', to='global_content.followus')),
            ],
            options={
                'verbose_name': 'Page Template',
                'verbose_name_plural': 'Page Templates',
                'db_table': 'page_template',
            },
        ),
    ]
