# Generated by Django 4.1.6 on 2023-03-12 23:39

import blog.models
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the blog post.', max_length=100)),
                ('slug', models.SlugField(blank=True, help_text="A URL-friendly version of the blog post's title.", max_length=255, null=True, unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='space-our-blog-backend/media'), upload_to='blog-images/', validators=[blog.models.validate_image])),
                ('initial_paragraph', models.TextField()),
                ('paragraph_heading', models.CharField(max_length=255)),
                ('quote', models.CharField(blank=True, max_length=255, null=True)),
                ('quote_writer', models.CharField(blank=True, max_length=255, null=True)),
                ('second_paragraph', models.TextField()),
                ('paragraph_after_image', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time when the blog post was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the blog post was last updated.')),
                ('most_recent_posts', models.BooleanField(blank=True, default=False, null=True)),
                ('featured_posts', models.BooleanField(blank=True, default=False, null=True)),
                ('older_posts', models.BooleanField(blank=True, default=False, null=True)),
                ('author', models.ForeignKey(help_text='The author of the blog post.', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'blog posts',
                'db_table': 'blog_posts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BlogPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='space-our-blog-backend/media'), upload_to='blog-images/', validators=[blog.models.validate_image])),
            ],
        ),
        migrations.CreateModel(
            name='BlogStepByStepGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbs_guide_number', models.PositiveSmallIntegerField(blank=True, help_text='Number of the sps guides on a post. can be used for multiple purposes', null=True)),
                ('main_heading', models.CharField(blank=True, help_text='The main heading of the step-by-step guide.', max_length=255, null=True)),
                ('main_content', models.TextField(blank=True, help_text='The main content of the step-by-step guide.', null=True)),
                ('blog_post', models.ForeignKey(blank=True, help_text='The blog post that this step-by-step guide belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_by_step_guides', to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'step-by-step guide',
                'verbose_name_plural': 'step-by-step guides',
                'db_table': 'step_by_step_guides',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost')),
            ],
        ),
        migrations.CreateModel(
            name='SBSGuideSubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(blank=True, help_text='The number of this subsection within the parent step-by-step guide.', null=True)),
                ('parent_guide', models.ForeignKey(blank=True, help_text='The parent step-by-step guide that this subsection belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='blog.blogstepbystepguide')),
            ],
            options={
                'verbose_name': 'step-by-step guide subsection',
                'verbose_name_plural': 'step-by-step guide subsections',
                'db_table': 'step_by_step_guide_subsections',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, help_text='The text of this subheading.', max_length=255, null=True)),
                ('parent_subsection', models.ForeignKey(blank=True, help_text='The parent subsection that this subheading belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subheadings', to='blog.sbsguidesubsection')),
            ],
            options={
                'verbose_name': 'subheading',
                'verbose_name_plural': 'subheadings',
                'db_table': 'subheadings',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, help_text='The text of this subcontent.', null=True)),
                ('parent_subsection', models.ForeignKey(blank=True, help_text='The parent subsection that this subcontent belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcontents', to='blog.sbsguidesubsection')),
            ],
            options={
                'verbose_name': 'subcontent',
                'verbose_name_plural': 'subcontents',
                'db_table': 'subcontents',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='sbsguidesubsection',
            name='subcontentss',
            field=models.ManyToManyField(help_text='The subcontents for this subsection.', related_name='subsections', to='blog.subcontent'),
        ),
        migrations.AddField(
            model_name='sbsguidesubsection',
            name='subheadingss',
            field=models.ManyToManyField(help_text='The subheadings for this subsection.', related_name='subsections', to='blog.subheading'),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reply_text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to=settings.AUTH_USER_MODEL)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment')),
            ],
        ),
        migrations.AddField(
            model_name='blogstepbystepguide',
            name='sbs_guides_subsections',
            field=models.ManyToManyField(help_text='The subsections within the step-by-step guide..', related_name='step_by_step_guides', to='blog.sbsguidesubsection'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_category', to='blog.category'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='post_images',
            field=models.ManyToManyField(blank=True, related_name='post_images', to='blog.blogpostimage'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='step_by_step_guide',
            field=models.ManyToManyField(related_name='blog_posts', to='blog.blogstepbystepguide'),
        ),
    ]
