# Generated by Django 4.1.7 on 2023-03-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogstepbystepguide',
            name='sub_fields_section',
            field=models.ManyToManyField(blank=True, null=True, to='blog.sbsguidesubsection'),
        ),
    ]
