# Generated by Django 4.1.7 on 2023-03-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogstepbystepguide',
            name='list_style',
            field=models.CharField(blank=True, choices=[('bulleted', 'Bulleted'), ('numbered', 'Numbered'), ('simple', 'Simple')], default='bulleted', help_text='The list style of the paragraph.', max_length=50, null=True),
        ),
    ]
