# Generated by Django 4.1.6 on 2023-02-23 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_name',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='author_id',
            new_name='author',
        ),
    ]
