# Generated by Django 4.1.6 on 2023-03-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='step_by_step_guide',
            field=models.ManyToManyField(blank=True, null=True, related_name='blog_posts', to='blog.blogstepbystepguide'),
        ),
    ]
