# Generated by Django 4.1.6 on 2023-03-11 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 11, 1, 24, 36, 108997, tzinfo=datetime.timezone.utc)),
        ),
    ]
