# Generated by Django 4.1.6 on 2023-03-12 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbsguidesubsection',
            name='sbs_g_sub_sec_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sbs_guide_sub_sec_to_parent', to='blog.blogstepbystepguide'),
        ),
        migrations.AlterField(
            model_name='sbsguidesubsection',
            name='sub_content',
            field=models.ManyToManyField(help_text='The sub content for the step-by-step guide.', related_name='sbs_guide_sub_content', to='blog.subcontent'),
        ),
    ]
