# Generated by Django 4.1.7 on 2023-03-21 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedPost',
            fields=[
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='featured_post', serialize=False, to='blog.blogpost')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_posts', to='blog.category')),
            ],
            options={
                'verbose_name_plural': 'featured posts',
            },
        ),
    ]
