# Generated by Django 4.1.6 on 2023-03-11 23:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 11, 23, 50, 29, 8952, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_images',
            field=models.ManyToManyField(related_name='post_images', to='blog.blogpostimage'),
        ),
        migrations.CreateModel(
            name='BlogParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs_list', to='blog.blogpost')),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='paragraphs',
            field=models.ManyToManyField(related_name='blog_posts', to='blog.blogparagraph'),
        ),
    ]
