# Generated by Django 4.1.7 on 2023-03-23 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_userprofile_email'),
        ('blog', '0002_featuredpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author_profile',
            field=models.ForeignKey(blank=True, help_text='The author of the blog post.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='UserProfile.userprofile'),
        ),
    ]
