# Generated by Django 4.1.7 on 2023-03-18 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogparagraph',
            options={},
        ),
        migrations.AlterModelTable(
            name='blogparagraph',
            table=None,
        ),
    ]
