# Generated by Django 4.1.6 on 2023-03-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_author_id_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='most_recent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='older',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
