# Generated by Django 4.1.7 on 2023-03-26 09:13

import blog.paragraph_with_sbs
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_author_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogparagraph',
            name='paragraph_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='space-our-blog-backend/media'), upload_to='blog-images/paragraph-images', validators=[blog.paragraph_with_sbs.validate_image]),
        ),
        migrations.AddField(
            model_name='blogstepbystepguide',
            name='sbs_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='space-our-blog-backend/media'), upload_to='blog-images/sbs-guide-images', validators=[blog.paragraph_with_sbs.validate_image]),
        ),
    ]
