# Generated by Django 4.1.6 on 2023-07-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogpost_paragraphs_remove_blogpost_quote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='post_images',
        ),
        migrations.DeleteModel(
            name='BlogPostImage',
        ),
    ]
