# Generated by Django 4.1.6 on 2023-03-12 00:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_created_at_alter_blogpost_post_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogStepByStepGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('main_content', models.TextField(blank=True, null=True)),
                ('sub_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='paragraphs',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 0, 3, 48, 926058, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='BlogParagraph',
        ),
        migrations.AddField(
            model_name='blogstepbystepguide',
            name='blog_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs_list', to='blog.blogpost'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='step_by_step_guide',
            field=models.ManyToManyField(related_name='blog_posts', to='blog.blogstepbystepguide'),
        ),
    ]
