# Generated by Django 4.1.6 on 2023-03-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_featured_blogpost_most_recent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='featured',
            new_name='featured_posts',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='most_recent',
            new_name='most_recent_posts',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='older',
            new_name='older_posts',
        ),
    ]
