# Generated by Django 4.1.7 on 2023-03-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogparagraph_paragraph_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topictype',
            name='topic_featured',
            field=models.ManyToManyField(blank=True, null=True, related_name='topic_featured_relation', to='blog.featuredpost'),
        ),
    ]
