# Generated by Django 4.1.6 on 2023-03-12 00:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogstepbystepguide_remove_blogpost_paragraphs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogstepbystepguide',
            name='sub_content',
        ),
        migrations.RemoveField(
            model_name='blogstepbystepguide',
            name='sub_heading',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 0, 14, 41, 466447, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='BlogPostSBSGuideSubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_content', models.TextField(blank=True, null=True)),
                ('blog_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections_list', to='blog.blogstepbystepguide')),
            ],
        ),
    ]
