# Generated by Django 4.1.6 on 2023-07-08 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_category_options_alter_category_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ('reply_text',), 'verbose_name_plural': 'replies'},
        ),
        migrations.AlterModelTable(
            name='reply',
            table='reply',
        ),
    ]
