# Generated by Django 4.1.7 on 2023-03-26 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_topictype_topic_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredpost',
            name='featured_topic_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.topictype'),
        ),
        migrations.AlterField(
            model_name='topictype',
            name='topic_featured',
            field=models.ManyToManyField(blank=True, related_name='topic_featured_relation', to='blog.featuredpost'),
        ),
    ]
