# Generated by Django 4.1.6 on 2023-03-12 00:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blogstepbystepguide_sub_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogstepbystepguide',
            name='sbs_guide_sub_fields',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sbs_guide_sub_fields_section', to='blog.blogpostsbsguidesubsection'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 0, 21, 4, 945268, tzinfo=datetime.timezone.utc)),
        ),
    ]
