# Generated by Django 4.1.6 on 2023-03-12 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogstepbystepguide_sbs_guide_sub_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 0, 30, 25, 95011, tzinfo=datetime.timezone.utc)),
        ),
        migrations.RemoveField(
            model_name='blogstepbystepguide',
            name='sbs_guide_sub_fields',
        ),
        migrations.AddField(
            model_name='blogstepbystepguide',
            name='sbs_guide_sub_fields',
            field=models.ManyToManyField(related_name='sbs_guide_sub_fields_section', to='blog.blogpostsbsguidesubsection'),
        ),
    ]
