# Generated by Django 4.1.6 on 2023-03-10 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogpost_paragraph_after_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 13, 48, 9, 104504, tzinfo=datetime.timezone.utc)),
        ),
    ]
