# Generated by Django 4.1.6 on 2023-03-12 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpost_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostsbsguidesubsection',
            name='blog_step',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 0, 31, 40, 388804, tzinfo=datetime.timezone.utc)),
        ),
    ]
