# Generated by Django 4.1.6 on 2023-03-12 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogstepbystepguide',
            name='blog_post',
            field=models.ForeignKey(blank=True, help_text='The blog post that this step-by-step guide belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_post_sbs', to='blog.blogpost'),
        ),
    ]
