# Generated by Django 4.1.7 on 2023-03-27 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_featuredpost_topicfeaturedpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topicfeaturedpost',
            options={'verbose_name_plural': 'topic featured posts'},
        ),
    ]
