# Generated by Django 4.1.6 on 2023-03-12 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogstepbystepguide_blog_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='subheading',
            name='sbs_heading_sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sbs_heading_parent', to='blog.sbsguidesubsection'),
        ),
    ]
