# Generated by Django 4.1.7 on 2023-03-27 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_topicfeaturedpost_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicfeaturedpost',
            name='category',
        ),
    ]
