# Generated by Django 4.1.7 on 2023-03-27 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_topicfeaturedpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='topic_featured_posts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_related_featured_posts', to='blog.topicfeaturedpost'),
        ),
    ]
