# Generated by Django 4.1.6 on 2023-03-12 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogpost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 0, 37, 28, 901565, tzinfo=datetime.timezone.utc)),
        ),
    ]
