# Generated by Django 4.1.6 on 2023-03-12 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blogpost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 0, 42, 11, 266153, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_images',
            field=models.ManyToManyField(null=True, related_name='post_images', to='blog.blogpostimage'),
        ),
    ]
