# Generated by Django 4.1.6 on 2023-03-10 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blogpost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 19, 31, 33, 571326, tzinfo=datetime.timezone.utc)),
        ),
    ]
