# Generated by Django 4.1.7 on 2023-03-27 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_topicfeaturedpost_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicfeaturedpost',
            name='post',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='featured_post', serialize=False, to='blog.blogpost'),
        ),
    ]
