# Generated by Django 4.1.6 on 2023-03-12 01:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_blogpost_created_at_alter_blogpost_post_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, help_text='The text of the sub content.', null=True)),
            ],
            options={
                'verbose_name': 'subcontent',
                'verbose_name_plural': 'subcontents',
                'db_table': 'sub_contents',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, help_text='The text of the subheading.', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'subheading',
                'verbose_name_plural': 'subheadings',
                'db_table': 'subheadings',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='blogpostsbsguidesubsection',
            options={'ordering': ['id'], 'verbose_name': 'step-by-step guide', 'verbose_name_plural': 'step-by-step guides'},
        ),
        migrations.RemoveField(
            model_name='blogpostsbsguidesubsection',
            name='sub_heading',
        ),
        migrations.AddField(
            model_name='blogpostsbsguidesubsection',
            name='blog_post',
            field=models.ForeignKey(blank=True, help_text='The blog post that this step-by-step guide belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_by_step_guides', to='blog.blogpost'),
        ),
        migrations.AddField(
            model_name='blogpostsbsguidesubsection',
            name='main_content',
            field=models.TextField(blank=True, help_text='The main content of the step-by-step guide.', null=True),
        ),
        migrations.AddField(
            model_name='blogpostsbsguidesubsection',
            name='main_heading',
            field=models.CharField(blank=True, help_text='The main heading of the step-by-step guide.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 1, 12, 25, 67080, tzinfo=datetime.timezone.utc)),
        ),
        migrations.RemoveField(
            model_name='blogpostsbsguidesubsection',
            name='sub_content',
        ),
        migrations.AlterModelTable(
            name='blogpostsbsguidesubsection',
            table='step_by_step_guides',
        ),
        migrations.AddField(
            model_name='blogpostsbsguidesubsection',
            name='subheadings',
            field=models.ManyToManyField(help_text='The subheadings for the step-by-step guide.', related_name='step_by_step_guides', to='blog.subheading'),
        ),
        migrations.AddField(
            model_name='blogpostsbsguidesubsection',
            name='sub_content',
            field=models.ManyToManyField(help_text='The sub content for the step-by-step guide.', related_name='step_by_step_guides', to='blog.subcontent'),
        ),
    ]
