# Generated by Django 4.1.6 on 2023-03-12 01:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_subcontent_subheading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostsbsguidesubsection',
            name='blog_post',
        ),
        migrations.RemoveField(
            model_name='blogpostsbsguidesubsection',
            name='main_content',
        ),
        migrations.RemoveField(
            model_name='blogpostsbsguidesubsection',
            name='main_heading',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 1, 26, 6, 951929, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='blogstepbystepguide',
            name='blog_post',
            field=models.ForeignKey(blank=True, help_text='The blog post that this step-by-step guide belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_by_step_guides', to='blog.blogpost'),
        ),
        migrations.AlterField(
            model_name='blogstepbystepguide',
            name='main_content',
            field=models.TextField(blank=True, help_text='The main content of the step-by-step guide.', null=True),
        ),
        migrations.AlterField(
            model_name='blogstepbystepguide',
            name='main_heading',
            field=models.CharField(blank=True, help_text='The main heading of the step-by-step guide.', max_length=255, null=True),
        ),
    ]
