# Generated by Django 4.1.7 on 2023-03-27 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_blogpost_topic_featured_posts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicfeaturedpost',
            name='featured_topic_type',
        ),
    ]
