# Generated by Django 4.1.7 on 2023-03-27 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_topicfeaturedpost_featured_topic_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topictype',
            old_name='topic',
            new_name='topic_name',
        ),
    ]
