# Generated by Django 4.1.6 on 2023-03-12 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_blogpostsbsguidesubsection_blog_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpostsbsguidesubsection',
            old_name='subheadings',
            new_name='sub_heading',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 2, 9, 56, 806306, tzinfo=datetime.timezone.utc)),
        ),
    ]
