# Generated by Django 4.1.6 on 2023-03-12 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_rename_subheadings_blogpostsbsguidesubsection_sub_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 2, 10, 11, 843670, tzinfo=datetime.timezone.utc)),
        ),
    ]
