# Generated by Django 4.1.7 on 2023-03-27 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_topicfeaturedpost_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topictype',
            name='topic_featured',
        ),
        migrations.DeleteModel(
            name='TopicFeaturedPost',
        ),
    ]
