# Generated by Django 4.1.6 on 2023-03-12 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_blogpost_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostsbsguidesubsection',
            name='sub_heading_number',
            field=models.IntegerField(blank=True, help_text='The subheadings number for the step-by-step guide.', null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 2, 35, 37, 89392, tzinfo=datetime.timezone.utc)),
        ),
    ]
