# Generated by Django 4.1.6 on 2023-03-12 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_blogpostsbsguidesubsection_sub_heading_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPostSBSGuideSubSection',
            new_name='SBSGuideSubSection',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 3, 14, 34, 966084, tzinfo=datetime.timezone.utc)),
        ),
    ]
