# Generated by Django 4.1.7 on 2023-03-27 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_topictype_topic_featured_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicFeaturedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_topic_type', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='featured_posts', to='blog.topictype')),
                ('post', models.ManyToManyField(blank=True, related_name='featured_post', to='blog.blogpost')),
            ],
            options={
                'verbose_name_plural': 'topic featured posts',
            },
        ),
    ]
