# Generated by Django 4.1.6 on 2023-03-12 03:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_rename_blogpostsbsguidesubsection_sbsguidesubsection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogstepbystepguide',
            name='sbs_guide_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of the sps guides on a post. can be used for multiple purposes', null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 3, 26, 9, 27940, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sbsguidesubsection',
            name='sub_heading_number',
            field=models.IntegerField(blank=True, help_text='The number the sub sections in each sbs guide within a post.used for multiple purposes', null=True),
        ),
    ]
