# Generated by Django 4.1.7 on 2023-03-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_topicfeaturedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='topictype',
            name='topic_featured_post',
            field=models.ManyToManyField(blank=True, null=True, related_name='topic_featured_posts', to='blog.topicfeaturedpost'),
        ),
    ]
