# Generated by Django 4.1.6 on 2023-03-12 03:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_blogstepbystepguide_sbs_guide_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 3, 26, 56, 531666, tzinfo=datetime.timezone.utc)),
        ),
    ]
