# Generated by Django 4.1.7 on 2023-03-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_topictype_topic_featured_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicfeaturedpost',
            name='post',
        ),
        migrations.AddField(
            model_name='topictype',
            name='post',
            field=models.ManyToManyField(blank=True, related_name='featured_post', to='blog.blogpost'),
        ),
    ]
