# Generated by Django 4.1.7 on 2023-03-18 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the about page.', max_length=100)),
                ('content', models.TextField(blank=True, help_text='The content of the about page.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time when the contact us page was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the contact us post was last updated.')),
                ('author', models.ForeignKey(help_text='The author of the contact us page.', on_delete=django.db.models.deletion.CASCADE, related_name='contact_us', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'contact us',
                'db_table': 'contact_us',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SBSGuideSubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbs_index', models.PositiveSmallIntegerField(blank=True, help_text='The number of this subsection within the parent step-by-step guide.', null=True)),
                ('blog_post', models.ForeignKey(help_text='The contact us page that this subsection belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='sbs_subsections', to='ContactUs.contactus')),
            ],
            options={
                'verbose_name': 'step-by-step guide subsection',
                'verbose_name_plural': 'step-by-step guide subsections',
                'db_table': 'step_by_step_guide_subsections_contact',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_index', models.PositiveSmallIntegerField(blank=True, help_text='The number of this subsection within the parent step-by-step guide.', null=True)),
                ('sub_heading', models.CharField(blank=True, help_text='The text of this subheading.', max_length=255, null=True)),
                ('sub_content', models.TextField(blank=True, help_text='The text of this subcontent.', null=True)),
                ('sbs_guide_sub_section', models.ForeignKey(help_text='The parent subsection that this subheading belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='sub_fields_parent', to='ContactUs.sbsguidesubsection')),
            ],
        ),
        migrations.CreateModel(
            name='StepByStepGuid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbs_guide_number', models.PositiveSmallIntegerField(blank=True, help_text='Number of the step-by-step guides on a post. Can be used for multiple purposes.', null=True)),
                ('main_heading', models.CharField(blank=True, help_text='The main heading of the step-by-step guide.', max_length=255, null=True)),
                ('main_content', models.TextField(blank=True, help_text='The main content of the step-by-step guide.', null=True)),
                ('blog_post', models.ForeignKey(help_text='The contact us page that this step-by-step guide belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='step_by_step_guides_contact', to='ContactUs.contactus')),
                ('sub_fields_section', models.ManyToManyField(blank=True, help_text='The subsections for this step-by-step guide.', to='ContactUs.sbsguidesubsection')),
            ],
            options={
                'verbose_name': 'step-by-step guide',
                'verbose_name_plural': 'step-by-step guides',
                'db_table': 'step_by_step_guides_contact',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='sbsguidesubsection',
            name='parent_guide',
            field=models.ForeignKey(help_text='The parent step-by-step guide that this subsection belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='ContactUs.stepbystepguid'),
        ),
        migrations.AddField(
            model_name='sbsguidesubsection',
            name='parent_subsection',
            field=models.ForeignKey(blank=True, help_text='The parent subsection that this subsection belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='ContactUs.sbsguidesubsection'),
        ),
        migrations.AddField(
            model_name='sbsguidesubsection',
            name='sub_headings_and_contents',
            field=models.ManyToManyField(help_text='The subcontents for this subsection.', related_name='sub_fields', to='ContactUs.subfields'),
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_title', models.CharField(blank=True, help_text='The title of the paragraph..', max_length=255, null=True)),
                ('paragraph_content', models.TextField(blank=True, help_text='The content of the paragraph..', null=True)),
                ('order', models.PositiveIntegerField(blank=True, default=0, help_text='The order in which the paragraph should appear in the contact us page..', null=True)),
                ('blog_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_paragraphs', to='ContactUs.contactus')),
            ],
        ),
        migrations.AddField(
            model_name='contactus',
            name='paragraphs',
            field=models.ManyToManyField(related_name='paragraphs', to='ContactUs.paragraph'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='step_by_step_guide',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='ContactUs.stepbystepguid'),
        ),
    ]
