# Generated by Django 4.1.7 on 2023-03-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactUs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisewithwellplusgood',
            name='paragraphs_advertise_well_good',
            field=models.ManyToManyField(blank=True, related_name='paragraphs_advertise_well_good', to='ContactUs.paragraph'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='paragraphs',
            field=models.ManyToManyField(blank=True, related_name='paragraphs', to='ContactUs.paragraph'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='paragraphs_privacy_policy',
            field=models.ManyToManyField(blank=True, related_name='paragraphs_privacy_policy', to='ContactUs.paragraph'),
        ),
    ]
