# Generated by Django 4.1.7 on 2023-03-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactUs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepbystepguide',
            name='list_style',
            field=models.CharField(blank=True, choices=[('simple', 'Simple'), ('bulleted', 'Bulleted'), ('bulleted', 'Bulleted'), ('numbered', 'Numbered'), ('asterisk', 'Asterisk'), ('dotted', 'Dotted')], default='simple', help_text='The list style of the paragraph.', max_length=50, null=True),
        ),
    ]
