# Generated by Django 4.1.7 on 2023-03-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactUs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragraph',
            old_name='blog_post',
            new_name='contact_us',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='step_by_step_guide',
            field=models.ManyToManyField(blank=True, related_name='contacts_us', to='ContactUs.stepbystepguid'),
        ),
    ]
