# Generated by Django 4.1.7 on 2023-03-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactUs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='step_by_step_guide',
            field=models.ManyToManyField(blank=True, related_name='posts_sbs', to='ContactUs.stepbystepguide'),
        ),
    ]
