# Generated by Django 4.1.7 on 2023-03-20 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ContactUs', '0002_alter_stepbystepguide_list_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepbystepguide',
            name='contact_us',
            field=models.ForeignKey(help_text='The post that this step-by-step guide belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='step_by_step_guides_contact_specific', to='ContactUs.contactus'),
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the about page.', max_length=100)),
                ('content', models.TextField(blank=True, help_text='The content of the about page.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time when the contact us page was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the contact us post was last updated.')),
                ('author_privacy_policy', models.ForeignKey(blank=True, help_text='The author of the contact us page.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_privacy_policy', to=settings.AUTH_USER_MODEL)),
                ('paragraphs_privacy_policy', models.ManyToManyField(blank=True, null=True, related_name='paragraphs_privacy_policy', to='ContactUs.paragraph')),
            ],
            options={
                'verbose_name_plural': 'contact us',
                'db_table': 'PrivacyPolicy',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='stepbystepguide',
            name='privacy_policy',
            field=models.ForeignKey(blank=True, help_text='The post that this step-by-step guide belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='privacy_policy', to='ContactUs.privacypolicy'),
        ),
    ]
