# Generated by Django 4.1.7 on 2023-03-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageTemplate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followus',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='followus',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='followus',
            name='pinterest_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='followus',
            name='twitter_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='followus',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
