# Generated by Django 4.1.7 on 2023-03-23 20:34

import UserManagement.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_user_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='space-our-blog-backend/media'), upload_to='profile-images/', validators=[UserManagement.models.validate_image]),
        ),
    ]
