# Generated by Django 4.1.6 on 2023-07-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'role', 'verbose_name_plural': 'users role'},
        ),
        migrations.AlterModelTable(
            name='role',
            table='role',
        ),
    ]
